language: php

php:
  - 5.6
  - 7

matrix:
  fast_finish: true

services:
  - postgresql

addons:
  postgresql: "9.3"

before_script:
  - psql -c "create role symfony login superuser password 'symfony';" -U postgres
  - psql -c "create database cms owner symfony;" -U postgres
  - composer selfupdate
  - composer install --prefer-dist
  - php ./app/console doctrine:schema:create --env=test
  - psql -c "INSERT INTO custom_user (id, username, password) VALUES (0, 'dcnobre@gmail.com', '$2y$10$CnkaGow4GAg1Xx0l7CHWAe37ciknx60LNnYVXucLie3ljk9mt5epO');" -d cms -U postgres

script:
  - mkdir -p build/logs
  - ./bin/phpunit -c app --coverage-clover build/logs/clover.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="8088c936e7e4c38a62a8bda5c95ca6775a1a802ff9d005244aba4fba96e5415d" --format=php-clover build/logs/clover.xml

after_script:
  - php ./bin/coveralls -v
