language: php

php:
  - 5.6
  - 7

matrix:
  fast_finish: true
  allow_failures:
    - php: 7

before_script:
  - composer selfupdate
  - composer install --dev --prefer-dist

script:
  - ./bin/phpunit -c app