language: php

php:
  - 5.6
  - 7

matrix:
  fast_finish: true
  allow_failures:
    - php: 7

services:
  - postgresql

addons:
  postgresql: "9.3"

before_script:
  - psql -c "create role symfony login superuser password 'symfony';" -U postgres
  - psql -c "create database cms owner symfony;" -U postgres
  - php ./app/console doctrine:schema:update --force
  - psql -c "INSERT INTO custom_user (username) VALUES ('dcnobre@gmail.com');" -U postgres
  - composer selfupdate
  - composer install --dev --prefer-dist

script:
  - ./bin/phpunit -c app --coverage-clover build/logs/clover.xml

after_script:
  - php ./bin/coveralls -v
