language: php

php:
  - 5.6
  - 7

matrix:
  fast_finish: true
  allow_failures:
    - php: 7

services:
  - postgresql

addons:
  postgresql: "9.3"

before_script:
  - psql -c "create role symfony login superuser password 'symfony';" -U postgres
  - psql -c 'create database cms owner symfony;' -U postgres
  - composer selfupdate
  - composer install --dev --prefer-dist

script:
  - mkdir -p build/logs
  - ./bin/phpunit -c app --coverage-clover coverage.xml

after_script:
  - php ./bin/coveralls -v
