# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\CustomUser: bcrypt
    role_hierarchy:
        # ROLE_ADMIN can access all that ROLE_USER can access
        ROLE_ADMIN: [ROLE_USER]
    providers:
        chain_providers:
            chain:
                providers: [user_db]
        user_db:
            entity: { class: AppBundle:CustomUser, property: username }
    firewalls:
        main:
            pattern: /.*
            form_login:
                login_path: /login
                check_path: /login-check
                default_target_path: /admin
            logout:
                path: /logout
                target: /
            security: true
            anonymous: true
            # @see http://symfony.com/doc/current/cookbook/security/remember_me.html
            remember_me:
                secret:   '%secret%'
                lifetime: 604800
                path:     /
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/cms/user, roles: ROLE_ADMIN }
        - { path: ^/cms/category, roles: ROLE_ADMIN }
        - { path: ^/cms/page, roles: ROLE_USER }
        - { path: ^/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
